apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  namespace: todoapp
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
